### ISSUE TITLE
不能子文件夹递归处理

### ISSUE THREAD

**Issue by congwiny** [Roger-WIN/GBKtoUTF-8#1]
只能一个个文件夹的选择，不能自动递归文件夹下的子文件夹

**Comment by jxncsq** [comment]
+1

**Comment by SuvanCheng** [comment]
期待作者更新，也期待自己有时间帮助更新

**Comment by Hu-Wentao** [comment]
+1

**Comment by Hu-Wentao** [comment]
找到一个[新的项目](https://github.com/kakakakakakakakakakakaka/gbktoutf8) 可以递归处理文件夹

**Comment by jeklau** [comment]
子文件夹+10086，另外发现部分文件需勾选“包含BOM”才能正常处理。

**Comment by Roger-WIN** [comment]
此功能已在 [v1.3.0](https://github.com/Roger-WIN/GBKtoUTF-8/releases/tag/v1.3.0) 中加入，请试用。

**Comment by Roger-WIN** [comment]
> 子文件夹 + 10086，另外发现部分文件需勾选 “包含 BOM” 才能正常处理。

后面这条麻烦开一个新的 issue。
