### ISSUE TITLE
文件夹不能手动输入，必须一层层点开

### ISSUE THREAD

**Issue by jxncsq** [Roger-WIN/GBKtoUTF-8#2]

**Comment by Roger-WIN** [comment]
涉及到路径的合法性和安全性，暂无计划支持该功能。

**Comment by Roger-WIN** [comment]
作为一种暂时的方案，推荐使用 [Listary](https://www.listary.com/) 软件的「切换到文件管理器中正在浏览的文件夹」功能。

![image](https://user-images.githubusercontent.com/25821208/120897776-6cd22600-c65a-11eb-8169-1023dc2adda2.png)

**Comment by Roger-WIN** [comment]
https://github.com/Roger-WIN/GBKtoUTF-8/releases/tag/v1.5.1

通过利用从 .NET Core 3 开始提供的将 [FolderBrowserDialog](https://docs.microsoft.com/zh-cn/dotnet/api/system.windows.forms.folderbrowserdialog) 控件升级为基于 COM 的控件，浏览文件夹的对话框弹窗现在已更新：

![image](https://user-images.githubusercontent.com/25821208/147403957-848b5b6d-37d7-4f1d-b8d5-ba4095519b4e.png)
