### ISSUE TITLE
出现“No data is available for encoding 936. For information on defining a custom encoding, see the documentation for the Encoding. RegisterProvider method.”

### ISSUE THREAD

**Issue by Nexvrek** [Roger-WIN/GBKtoUTF-8#5]

**Comment by Roger-WIN** [comment]
麻烦描述一下复现的步骤。

**Comment by Nexvrek** [comment]
Steps 
Step 1: (‎2022/‎8/‎5 21:39:50) 用户在"GBK 转 UTF-8 (窗口)"上左键单击(在"GBK 转 UTF-8"中)
 第 1 步屏幕截图。 
Step 2: (‎2022/‎8/‎5 21:39:52) 用户在"选择 (按钮)"上左键单击(在"GBK 转 UTF-8"中)
 第 2 步屏幕截图。 
Step 3: (‎2022/‎8/‎5 21:39:54) 用户在"选择文件夹 (按钮)"上左键单击(在"选择文件夹"中)
 第 3 步屏幕截图。 
Step 4: (‎2022/‎8/‎5 21:39:57) 用户在"覆盖原文件 (复选框)"上左键单击(在"GBK 转 UTF-8"中)
 第 4 步屏幕截图。 
Step 5: (‎2022/‎8/‎5 21:39:59) 用户在"转换成功后打开文件夹 (复选框)"上左键单击(在"GBK 转 UTF-8"中)
 第 5 步屏幕截图。 
Step 6: (‎2022/‎8/‎5 21:40:01) 用户在"包含子文件夹 (复选框)"上左键单击(在"GBK 转 UTF-8"中)
 第 6 步屏幕截图。 
Step 7: (‎2022/‎8/‎5 21:40:03) 用户在"转换 (按钮)"上左键单击(在"GBK 转 UTF-8"中)
 第 7 步屏幕截图。 
Step 8: (‎2022/‎8/‎5 21:40:06) 用户在"GBK 转 UTF-8 (窗口)"上鼠标拖动开始
 第 8 步屏幕截图。 
Step 9: (‎2022/‎8/‎5 21:40:07) 用户在"GBK 转 UTF-8 (窗口)"上鼠标拖动结束
 第 9 步屏幕截图。 
Step 10: (‎2022/‎8/‎5 21:40:09) 用户在"确定 (按钮)"上左键单击
 
第 10 步屏幕截图。 
记录会话: ‎2022/‎8/‎5 21:39:47 - 21:40:10
记录的步骤: 10, 丢失的步骤: 0, 其他错误: 0
操作系统: 22000.1.amd64fre.co_release.210604-1628 10.0.0.0.2.48
步骤 1: 用户在"GBK 转 UTF-8 (窗口)"上左键单击(在"GBK 转 UTF-8"中)
程序: GBK.to.UTF-8, 1.5.1.0, Roger-WIN, GBK.TO.UTF-8_V1.5.1_WITH-RUNTIME.EXE, GBK.TO.UTF-8_V1.5.1_WITH-RUNTIME.EXE
用户界面元素: GBK 转 UTF-8, WindowsForms10.Window.8.app.0.378734a_r3_ad1

步骤 2: 用户在"选择 (按钮)"上左键单击(在"GBK 转 UTF-8"中)
程序: GBK.to.UTF-8, 1.5.1.0, Roger-WIN, GBK.TO.UTF-8_V1.5.1_WITH-RUNTIME.EXE, GBK.TO.UTF-8_V1.5.1_WITH-RUNTIME.EXE
用户界面元素: 选择, WindowsForms10.Button.app.0.378734a_r3_ad1, WindowsForms10.Window.8.app.0.378734a_r3_ad1, GBK 转 UTF-8, WindowsForms10.Window.8.app.0.378734a_r3_ad1

步骤 3: 用户在"选择文件夹 (按钮)"上左键单击(在"选择文件夹"中)
程序: GBK.to.UTF-8, 1.5.1.0, Roger-WIN, GBK.TO.UTF-8_V1.5.1_WITH-RUNTIME.EXE, GBK.TO.UTF-8_V1.5.1_WITH-RUNTIME.EXE
用户界面元素: 选择文件夹, Button, 选择文件夹, #32770, GBK 转 UTF-8, WindowsForms10.Window.8.app.0.378734a_r3_ad1

步骤 4: 用户在"覆盖原文件 (复选框)"上左键单击(在"GBK 转 UTF-8"中)
程序: GBK.to.UTF-8, 1.5.1.0, Roger-WIN, GBK.TO.UTF-8_V1.5.1_WITH-RUNTIME.EXE, GBK.TO.UTF-8_V1.5.1_WITH-RUNTIME.EXE
用户界面元素: 覆盖原文件, WindowsForms10.Button.app.0.378734a_r3_ad1, WindowsForms10.Window.8.app.0.378734a_r3_ad1, GBK 转 UTF-8, WindowsForms10.Window.8.app.0.378734a_r3_ad1

步骤 5: 用户在"转换成功后打开文件夹 (复选框)"上左键单击(在"GBK 转 UTF-8"中)
程序: GBK.to.UTF-8, 1.5.1.0, Roger-WIN, GBK.TO.UTF-8_V1.5.1_WITH-RUNTIME.EXE, GBK.TO.UTF-8_V1.5.1_WITH-RUNTIME.EXE
用户界面元素: 转换成功后打开文件夹, WindowsForms10.Button.app.0.378734a_r3_ad1, WindowsForms10.Window.8.app.0.378734a_r3_ad1, GBK 转 UTF-8, WindowsForms10.Window.8.app.0.378734a_r3_ad1

步骤 6: 用户在"包含子文件夹 (复选框)"上左键单击(在"GBK 转 UTF-8"中)
程序: GBK.to.UTF-8, 1.5.1.0, Roger-WIN, GBK.TO.UTF-8_V1.5.1_WITH-RUNTIME.EXE, GBK.TO.UTF-8_V1.5.1_WITH-RUNTIME.EXE
用户界面元素: 包含子文件夹, WindowsForms10.Button.app.0.378734a_r3_ad1, WindowsForms10.Window.8.app.0.378734a_r3_ad1, GBK 转 UTF-8, WindowsForms10.Window.8.app.0.378734a_r3_ad1

步骤 7: 用户在"转换 (按钮)"上左键单击(在"GBK 转 UTF-8"中)
程序: GBK.to.UTF-8, 1.5.1.0, Roger-WIN, GBK.TO.UTF-8_V1.5.1_WITH-RUNTIME.EXE, GBK.TO.UTF-8_V1.5.1_WITH-RUNTIME.EXE
用户界面元素: 转换, WindowsForms10.Button.app.0.378734a_r3_ad1, WindowsForms10.Window.8.app.0.378734a_r3_ad1, GBK 转 UTF-8, WindowsForms10.Window.8.app.0.378734a_r3_ad1

步骤 8: 用户在"GBK 转 UTF-8 (窗口)"上鼠标拖动开始
程序: GBK.to.UTF-8, 1.5.1.0, Roger-WIN, GBK.TO.UTF-8_V1.5.1_WITH-RUNTIME.EXE, GBK.TO.UTF-8_V1.5.1_WITH-RUNTIME.EXE
用户界面元素: #32770, GBK 转 UTF-8, WindowsForms10.Window.8.app.0.378734a_r3_ad1

步骤 9: 用户在"GBK 转 UTF-8 (窗口)"上鼠标拖动结束
程序: GBK.to.UTF-8, 1.5.1.0, Roger-WIN, GBK.TO.UTF-8_V1.5.1_WITH-RUNTIME.EXE, GBK.TO.UTF-8_V1.5.1_WITH-RUNTIME.EXE
用户界面元素: #32770, GBK 转 UTF-8, WindowsForms10.Window.8.app.0.378734a_r3_ad1

步骤 10: 用户在"确定 (按钮)"上左键单击
程序: GBK.to.UTF-8, 1.5.1.0, Roger-WIN, GBK.TO.UTF-8_V1.5.1_WITH-RUNTIME.EXE, GBK.TO.UTF-8_V1.5.1_WITH-RUNTIME.EXE
用户界面元素: 确定, Button, #32770, GBK 转 UTF-8, WindowsForms10.Window.8.app.0.378734a_r3_ad1


具体可查看文档
[Steps.docx](https://github.com/Roger-WIN/GBKtoUTF-8/files/9269474/Steps.docx)

**Comment by MrLeekon** [comment]
Win11 存在同样问题

**Comment by Roger-WIN** [comment]
已发布[新版本](https://github.com/Roger-WIN/GBKtoUTF-8/releases/tag/v1.5.3)修复此问题。
