### ISSUE TITLE
输出到其他文件夹时，可以不更改文件名吗

### ISSUE THREAD

**Issue by L-Super** [Roger-WIN/GBKtoUTF-8#6]

**Comment by Roger-WIN** [comment]
考虑之后，我打算提供一个选项控制是否给文件名加上后缀，来避免意外地将文件覆盖的情况。

**Comment by L-Super** [comment]
我觉得加一个判断就可以了 ，当勾选上输出到其他文件夹的时候 ，如果不是原文件夹，那就文件名不改，如果是原文件夹就弹一个弹窗

**Comment by Roger-WIN** [comment]
弹窗可以弄。
另外，你要知道本工具提供了“包含 BOM”的功能，包含或不包含两种情况下的文件名后缀是不同的。想象这样一种情形，先后将包含 BOM 和不包含 BOM 两种情况输出到了同一个目录（非原文件夹），这时如果带上后缀可以避免两次输出的文件相互覆盖；而不带后缀就会导致覆盖，这可能不是使用者所希望的。
当然，这种情况可能比较少，听起来像伪需求😂。因此我只是保险起见。

**Comment by L-Super** [comment]
那我说一下我的需求吧，我目前的需求是把所有的.cpp .h的文件编码转换成UTF-8。如果转换后文件重命名了，那我还得再进行一次文件批量重命名

**Comment by Roger-WIN** [comment]
所以我说弄一个「添加文件名后缀」的选项嘛，默认不勾选，既能够不改动文件名，又能给有需要的人避免错误覆盖文件。当然，弹窗也弄，在检测到输出到相同文件夹时弹出。

**Comment by L-Super** [comment]
嗯嗯，顺便催更一下😏

**Comment by Roger-WIN** [comment]
已发布[新版本](https://github.com/Roger-WIN/GBKtoUTF-8/releases/tag/v1.6.0)解决此问题。
